### ISSUE TITLE
Библиотека JSON-simple

### ISSUE THREAD

**Issue by d-frolov** [saidgadjiev/SpaceHockeyServer#1]
1. Когда в проект затягиваете библиотеки, то по правилам хорошего тона не стоит кидать в корень проекта, а например сделать папочку ./lib/ или ./vendor/  или что-то подобное. Структурирование разнотипных компонентов по папкам - залог чистоты и порядка.
2. См. класс PageGenerator. Не стоит бездумно давить инспекции. Они указывают на проблемное место. В данном случае метод put принимает нетипизированные данные. Это не очень хорошо, и потенциально проблемное место.
3. Я рекомендую заменить использование библиотеки JSON-simple на GSON 
   https://github.com/google/gson
   Там и maven репозиторий есть.

**Comment by saidgadjiev** [comment]
Исправил.
