### ISSUE TITLE
в Set и HashMap класть в качестве ключей неизменные объекты

### ISSUE THREAD

**Issue by KSolovyev** [saidgadjiev/SpaceHockeyServer#10]
GameMechanics.playerToGame - после того как мы сделаем Player.incrementScore, найти gameSession станет невозможно, т.к. у объекта Player изменится хеш

**Comment by KSolovyev** [comment]
Можете проверить это в тестах

**Comment by saidgadjiev** [comment]
Заменил на TreeMap().

**Comment by KSolovyev** [comment]
Решение не самое удачное. Здесь напрашивается замена Player на long playerId  или на крайний случай String playerName.

**Comment by saidgadjiev** [comment]
А если переопределить hashCode() в Player например так:
        final int seed = 37;
        int result = 1;
        result = seed \* result + ((name == null) ? 0 : name.hashCode());
        return result;

**Comment by KSolovyev** [comment]
Вы можете так сделать, но я бы очень не советовал играться с хэш-функцией. Работать будет, но любой человек, читающий ваш код будет в недоумении.
. Моя рекомендация для ключа хеш-мапа и хеш-сета - это неизменяемый объект, у которого есть однозначное взаимное соостветствие с объектом, связь которого вы хотите установить посредством хеш-коллекции. В данном случае подходит имя аккаунта пользователя, уникальность которого вы гарантируете на моменте регистрации.И еще лучше подходит id из базы данных, который еще и гарантирует отстутствие коллизий

**Comment by saidgadjiev** [comment]
Спасибо, понял. Исправил.
