### ISSUE TITLE
Отделить транспорт от игровой логики

### ISSUE THREAD

**Issue by KSolovyev** [saidgadjiev/SpaceHockeyServer#11]
В идеале - транспорт ничего не должен знать об игре, только о том, что есть сообщения, и они обрабатываются. Игра ничего не должна знать о транспорте, только о том, что есть игроки и об операциях с ними. Игрок должен знать о транспорте на отправку, но сообщения должен принимать только от GM. 
Хорошее упражнение здесь - подумать как реализовать систему мирового чата на том же транспорте(websocket) и как сделать серверного бота, который заменит второго игрока, если посетителей не так много. Реализовывать все это не надо, но подумать как изменится архитектура с учетом этих требований стоит

**Comment by saidgadjiev** [comment]
Сделал.
