### ISSUE TITLE
Неиспользуемые функции

### ISSUE THREAD

**Issue by KSolovyev** [saidgadjiev/SpaceHockeyServer#12]
Советую добавлять интерфейсы по ходу разработки функционала, а не заранее. Если речь идет не о разработке архитектуры (а чаще всего речь идет не о ней), то добавлять неиспользуемые функции не надо.
GameSession.getSelfPlayer - только в тестах
Ball - все серое
WebSocketService - все, что серое

**Comment by saidgadjiev** [comment]
Исправил.
