### ISSUE TITLE
Player.myPosition - должно быть типа enum

### ISSUE THREAD

**Issue by KSolovyev** [saidgadjiev/SpaceHockeyServer#14]
Если у вас myPosition принимает 2 значения, то стоит его сделать типа enum. Или вообще boolean. например

```
public enum Position {
        UPPER,
        LOWER;

        public Position getOposite() {
            if (this == UPPER) {
                return LOWER;
            }
            return UPPER;
        }
}
```

тогда можно будет использовать такую конструкцию:

```
final  Position myPosition = Position.UPPER;
final Position enemyPosition = myPosition.getOposite()

```

**Comment by saidgadjiev** [comment]
Исправил.

**Comment by KSolovyev** [comment]
Так как вы добавили еще одно поле в enum, то нужно его поддержать в функции getOposite. Я подозреваю, что getOposite(Position.NONE) = Position.NONE

**Comment by saidgadjiev** [comment]
Нельзя ли просто пользоваться полями enum без getOposite()?

**Comment by KSolovyev** [comment]
Можно, почему нет? Я привел этот код просто как пример
