### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by d-frolov** [saidgadjiev/SpaceHockeyServer#3]
Очень зря в ингор добавили папку .idea/*
Там, конечно есть ненужные файлы, врорде конфигурации воркспейса, но при этом там содержится ряд существенных конфигурационных файлов, вроде modules.xml, описание билиотек и т.п. Мне приходится вручную доконфигурировать проект

PS. Если json-simple не нужен, то стоит его вообще выкинуть из проекта и не таскать

**Comment by saidgadjiev** [comment]
Добавил в pom.xml зависимость gson.
